package com.tateca.tatecabackend.exception;

/**
 * Centralized error codes for internationalization.
 * Format: DOMAIN.ERROR_TYPE
 *
 * Benefits:
 * - Type-safe error code references
 * - Easy to search/grep across codebase
 * - Self-documenting error taxonomy
 * - Client-side can handle specific errors (e.g., navigate to signup on USER.NOT_FOUND)
 */
public enum ErrorCode {
    // User Domain Errors
    USER_NOT_FOUND("USER.NOT_FOUND"),
    USER_ALREADY_EXISTS("USER.ALREADY_EXISTS"),

    // Auth User Domain Errors
    AUTH_USER_NOT_FOUND("AUTH.USER_NOT_FOUND"),
    AUTH_EMAIL_ALREADY_EXISTS("AUTH.EMAIL_ALREADY_EXISTS"),

    // Group Domain Errors
    GROUP_NOT_FOUND("GROUP.NOT_FOUND"),
    GROUP_MEMBER_NOT_FOUND("GROUP.MEMBER_NOT_FOUND"),
    GROUP_FULL("GROUP.FULL"),
    GROUP_MAX_COUNT_EXCEEDED("GROUP.MAX_COUNT_EXCEEDED"),
    GROUP_ALREADY_JOINED("GROUP.ALREADY_JOINED"),
    GROUP_INVALID_TOKEN("GROUP.INVALID_TOKEN"),

    // Transaction Domain Errors
    TRANSACTION_NOT_FOUND("TRANSACTION.NOT_FOUND"),
    TRANSACTION_INVALID_AMOUNT("TRANSACTION.INVALID_AMOUNT"),
    TRANSACTION_INVALID_OBLIGATIONS("TRANSACTION.INVALID_OBLIGATIONS"),
    TRANSACTION_NOT_CREATOR("TRANSACTION.NOT_CREATOR"),

    // Exchange Rate Domain Errors
    EXCHANGE_RATE_NOT_FOUND("EXCHANGE_RATE.NOT_FOUND"),

    // Validation Errors
    VALIDATION_FAILED("VALIDATION.FAILED"),
    VALIDATION_FIELD_REQUIRED("VALIDATION.FIELD_REQUIRED"),
    VALIDATION_FIELD_INVALID_FORMAT("VALIDATION.FIELD_INVALID_FORMAT"),
    VALIDATION_FIELD_LENGTH("VALIDATION.FIELD_LENGTH"),

    // Database Errors
    DATABASE_ERROR("DATABASE.ERROR"),
    DATABASE_CONSTRAINT_VIOLATION("DATABASE.CONSTRAINT_VIOLATION"),

    // Request Errors
    REQUEST_INVALID_FORMAT("REQUEST.INVALID_FORMAT"),
    REQUEST_INVALID_PARAMETER("REQUEST.INVALID_PARAMETER"),
    REQUEST_UNSUPPORTED_MEDIA_TYPE("REQUEST.UNSUPPORTED_MEDIA_TYPE"),

    // System Errors
    SYSTEM_INTERNAL_ERROR("SYSTEM.INTERNAL_ERROR"),
    SYSTEM_UNEXPECTED_ERROR("SYSTEM.UNEXPECTED_ERROR");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
