INSERT INTO currency_names (currency_code, jp_currency_name, eng_currency_name, jp_country_name, eng_country_name, is_active)
VALUES
    ('AED', 'UAEディルハム', 'UAE Dirham', 'アラブ首長国連邦', 'United Arab Emirates', 1),
    ('AFN', 'アフガニ', 'Afghan Afghani', 'アフガニスタン', 'Afghanistan', 1),
    ('ALL', 'アルバニア・レク', 'Albanian Lek', 'アルバニア', 'Albania', 1),
    ('AMD', 'アルメニア・ドラム', 'Armenian Dram', 'アルメニア', 'Armenia', 1),
    ('ANG', 'オランダ領アンティル・ギルダー', 'Netherlands Antillian Guilder', 'オランダ領アンティル', 'Netherlands Antilles', 1),
    ('AOA', 'アンゴラ・クワンザ', 'Angolan Kwanza', 'アンゴラ', 'Angola', 1),
    ('ARS', 'アルゼンチン・ペソ', 'Argentine Peso', 'アルゼンチン', 'Argentina', 1),
    ('AUD', 'オーストラリア・ドル', 'Australian Dollar', 'オーストラリア', 'Australia', 1),
    ('AWG', 'アルバ・フローリン', 'Aruban Florin', 'アルバ', 'Aruba', 1),
    ('AZN', 'アゼルバイジャン・マナット', 'Azerbaijani Manat', 'アゼルバイジャン', 'Azerbaijan', 1),
    ('BAM', 'ボスニア・ヘルツェゴビナ・マルク', 'Bosnia and Herzegovina Mark', 'ボスニア・ヘルツェゴビナ', 'Bosnia and Herzegovina', 1),
    ('BBD', 'バルバドス・ドル', 'Barbados Dollar', 'バルバドス', 'Barbados', 1),
    ('BDT', 'バングラデシュ・タカ', 'Bangladeshi Taka', 'バングラデシュ', 'Bangladesh', 1),
    ('BGN', 'ブルガリア・レフ', 'Bulgarian Lev', 'ブルガリア', 'Bulgaria', 1),
    ('BHD', 'バーレーン・ディナール', 'Bahraini Dinar', 'バーレーン', 'Bahrain', 1),
    ('BIF', 'ブルンジ・フラン', 'Burundian Franc', 'ブルンジ', 'Burundi', 1),
    ('BMD', 'バミューダ・ドル', 'Bermudian Dollar', 'バミューダ', 'Bermuda', 1),
    ('BND', 'ブルネイ・ドル', 'Brunei Dollar', 'ブルネイ', 'Brunei', 1),
    ('BOB', 'ボリビア・ボリビアーノ', 'Bolivian Boliviano', 'ボリビア', 'Bolivia', 1),
    ('BRL', 'ブラジル・レアル', 'Brazilian Real', 'ブラジル', 'Brazil', 1),
    ('BSD', 'バハマ・ドル', 'Bahamian Dollar', 'バハマ', 'Bahamas', 1),
    ('BTN', 'ブータン・ヌルトルム', 'Bhutanese Ngultrum', 'ブータン', 'Bhutan', 1),
    ('BWP', 'ボツワナ・プラ', 'Botswana Pula', 'ボツワナ', 'Botswana', 1),
    ('BYN', 'ベラルーシ・ルーブル', 'Belarusian Ruble', 'ベラルーシ', 'Belarus', 1),
    ('BZD', 'ベリーズ・ドル', 'Belize Dollar', 'ベリーズ', 'Belize', 1),
    ('CAD', 'カナダ・ドル', 'Canadian Dollar', 'カナダ', 'Canada', 1),
    ('CDF', 'コンゴ・フラン', 'Congolese Franc', 'コンゴ', 'Democratic Republic of the Congo', 1),
    ('CHF', 'スイス・フラン', 'Swiss Franc', 'スイス', 'Switzerland', 1),
    ('CLP', 'チリ・ペソ', 'Chilean Peso', 'チリ', 'Chile', 1),
    ('CNY', '中国元', 'Chinese Renminbi', '中国', 'China', 1),
    ('COP', 'コロンビア・ペソ', 'Colombian Peso', 'コロンビア', 'Colombia', 1),
    ('CRC', 'コスタリカ・コロン', 'Costa Rican Colon', 'コスタリカ', 'Costa Rica', 1),
    ('CUP', 'キューバ・ペソ', 'Cuban Peso', 'キューバ', 'Cuba', 1),
    ('CVE', 'カーボベルデ・エスクード', 'Cape Verdean Escudo', 'カーボベルデ', 'Cape Verde', 1),
    ('CZK', 'チェコ・コルナ', 'Czech Koruna', 'チェコ', 'Czech Republic', 1),
    ('DJF', 'ジブチ・フラン', 'Djiboutian Franc', 'ジブチ', 'Djibouti', 1),
    ('DKK', 'デンマーク・クローネ', 'Danish Krone', 'デンマーク', 'Denmark', 1),
    ('DOP', 'ドミニカ・ペソ', 'Dominican Peso', 'ドミニカ共和国', 'Dominican Republic', 1),
    ('DZD', 'アルジェリア・ディナール', 'Algerian Dinar', 'アルジェリア', 'Algeria', 1),
    ('EGP', 'エジプト・ポンド', 'Egyptian Pound', 'エジプト', 'Egypt', 1),
    ('ERN', 'エリトリア・ナクファ', 'Eritrean Nakfa', 'エリトリア', 'Eritrea', 1),
    ('ETB', 'エチオピア・ビル', 'Ethiopian Birr', 'エチオピア', 'Ethiopia', 1),
    ('EUR', 'ユーロ', 'Euro', 'ヨーロッパ連合', 'European Union', 1),
    ('FJD', 'フィジー・ドル', 'Fiji Dollar', 'フィジー', 'Fiji', 1),
    ('FKP', 'フォークランド諸島・ポンド', 'Falkland Islands Pound', 'フォークランド諸島', 'Falkland Islands', 1),
    ('FOK', 'フェロー諸島・クローナ', 'Faroese Króna', 'フェロー諸島', 'Faroe Islands', 1),
    ('GBP', 'ポンド', 'Pound Sterling', 'イギリス', 'United Kingdom', 1),
    ('GEL', 'ジョージア・ラリ', 'Georgian Lari', 'ジョージア', 'Georgia', 1),
    ('GGP', 'ガーンジー・ポンド', 'Guernsey Pound', 'ガーンジー', 'Guernsey', 1),
    ('GHS', 'ガーナ・セディ', 'Ghanaian Cedi', 'ガーナ', 'Ghana', 1),
    ('GIP', 'ジブラルタル・ポンド', 'Gibraltar Pound', 'ジブラルタル', 'Gibraltar', 1),
    ('GMD', 'ガンビア・ダラシ', 'Gambian Dalasi', 'ガンビア', 'The Gambia', 1),
    ('GNF', 'ギニア・フラン', 'Guinean Franc', 'ギニア', 'Guinea', 1),
    ('GTQ', 'グアテマラ・ケツァール', 'Guatemalan Quetzal', 'グアテマラ', 'Guatemala', 1),
    ('GYD', 'ガイアナ・ドル', 'Guyanese Dollar', 'ガイアナ', 'Guyana', 1),
    ('HKD', '香港・ドル', 'Hong Kong Dollar', '香港', 'Hong Kong', 1),
    ('HNL', 'ホンジュラス・レンピラ', 'Honduran Lempira', 'ホンジュラス', 'Honduras', 1),
    ('HRK', 'クロアチア・クーナ', 'Croatian Kuna', 'クロアチア', 'Croatia', 1),
    ('HTG', 'ハイチ・グルード', 'Haitian Gourde', 'ハイチ', 'Haiti', 1),
    ('HUF', 'ハンガリー・フォリント', 'Hungarian Forint', 'ハンガリー', 'Hungary', 1),
    ('IDR', 'インドネシア・ルピア', 'Indonesian Rupiah', 'インドネシア', 'Indonesia', 1),
    ('ILS', 'イスラエル・新シェケル', 'Israeli New Shekel', 'イスラエル', 'Israel', 1),
    ('IMP', 'マン島・ポンド', 'Manx Pound', 'マン島', 'Isle of Man', 1),
    ('INR', 'インド・ルピー', 'Indian Rupee', 'インド', 'India', 1),
    ('IQD', 'イラク・ディナール', 'Iraqi Dinar', 'イラク', 'Iraq', 1),
    ('IRR', 'イラン・リアル', 'Iranian Rial', 'イラン', 'Iran', 1),
    ('ISK', 'アイスランド・クローナ', 'Icelandic Króna', 'アイスランド', 'Iceland', 1),
    ('JEP', 'ジャージー・ポンド', 'Jersey Pound', 'ジャージー', 'Jersey', 1),
    ('JMD', 'ジャマイカ・ドル', 'Jamaican Dollar', 'ジャマイカ', 'Jamaica', 1),
    ('JOD', 'ヨルダン・ディナール', 'Jordanian Dinar', 'ヨルダン', 'Jordan', 1),
    ('JPY', '日本円', 'Japanese Yen', '日本', 'Japan', 1),
    ('KES', 'ケニア・シリング', 'Kenyan Shilling', 'ケニア', 'Kenya', 1),
    ('KGS', 'キルギス・ソム', 'Kyrgyzstani Som', 'キルギス', 'Kyrgyzstan', 1),
    ('KHR', 'カンボジア・リエル', 'Cambodian Riel', 'カンボジア', 'Cambodia', 1),
    ('KID', 'キリバス・ドル', 'Kiribati Dollar', 'キリバス', 'Kiribati', 1),
    ('KMF', 'コモロ・フラン', 'Comorian Franc', 'コモロ', 'Comoros', 1),
    ('KRW', '韓国・ウォン', 'South Korean Won', '韓国', 'South Korea', 1),
    ('KWD', 'クウェート・ディナール', 'Kuwaiti Dinar', 'クウェート', 'Kuwait', 1),
    ('KYD', 'ケイマン諸島・ドル', 'Cayman Islands Dollar', 'ケイマン諸島', 'Cayman Islands', 1),
    ('KZT', 'カザフスタン・テンゲ', 'Kazakhstani Tenge', 'カザフスタン', 'Kazakhstan', 1),
    ('LAK', 'ラオス・キップ', 'Lao Kip', 'ラオス', 'Laos', 1),
    ('LBP', 'レバノン・ポンド', 'Lebanese Pound', 'レバノン', 'Lebanon', 1),
    ('LKR', 'スリランカ・ルピー', 'Sri Lanka Rupee', 'スリランカ', 'Sri Lanka', 1),
    ('LRD', 'リベリア・ドル', 'Liberian Dollar', 'リベリア', 'Liberia', 1),
    ('LSL', 'レソト・ロティ', 'Lesotho Loti', 'レソト', 'Lesotho', 1),
    ('LYD', 'リビア・ディナール', 'Libyan Dinar', 'リビア', 'Libya', 1),
    ('MAD', 'モロッコ・ディルハム', 'Moroccan Dirham', 'モロッコ', 'Morocco', 1),
    ('MDL', 'モルドバ・レウ', 'Moldovan Leu', 'モルドバ', 'Moldova', 1),
    ('MGA', 'マダガスカル・アリアリ', 'Malagasy Ariary', 'マダガスカル', 'Madagascar', 1),
    ('MKD', '北マケドニア・デナル', 'Macedonian Denar', '北マケドニア', 'North Macedonia', 1),
    ('MMK', 'ミャンマー・チャット', 'Burmese Kyat', 'ミャンマー', 'Myanmar', 1),
    ('MNT', 'モンゴル・トグログ', 'Mongolian Tögrög', 'モンゴル', 'Mongolia', 1),
    ('MOP', 'マカオ・パタカ', 'Macanese Pataca', 'マカオ', 'Macau', 1),
    ('MRU', 'モーリタニア・ウギーヤ', 'Mauritanian Ouguiya', 'モーリタニア', 'Mauritania', 1),
    ('MUR', 'モーリシャス・ルピー', 'Mauritian Rupee', 'モーリシャス', 'Mauritius', 1),
    ('MVR', 'モルディブ・ルフィア', 'Maldivian Rufiyaa', 'モルディブ', 'Maldives', 1),
    ('MWK', 'マラウイ・クワチャ', 'Malawian Kwacha', 'マラウイ', 'Malawi', 1),
    ('MXN', 'メキシコ・ペソ', 'Mexican Peso', 'メキシコ', 'Mexico', 1),
    ('MYR', 'マレーシア・リンギット', 'Malaysian Ringgit', 'マレーシア', 'Malaysia', 1),
    ('MZN', 'モザンビーク・メティカル', 'Mozambican Metical', 'モザンビーク', 'Mozambique', 1),
    ('NAD', 'ナミビア・ドル', 'Namibian Dollar', 'ナミビア', 'Namibia', 1),
    ('NGN', 'ナイジェリア・ナイラ', 'Nigerian Naira', 'ナイジェリア', 'Nigeria', 1),
    ('NIO', 'ニカラグア・コルドバ', 'Nicaraguan Córdoba', 'ニカラグア', 'Nicaragua', 1),
    ('NOK', 'ノルウェー・クローネ', 'Norwegian Krone', 'ノルウェー', 'Norway', 1),
    ('NPR', 'ネパール・ルピー', 'Nepalese Rupee', 'ネパール', 'Nepal', 1),
    ('NZD', 'ニュージーランド・ドル', 'New Zealand Dollar', 'ニュージーランド', 'New Zealand', 1),
    ('OMR', 'オマーン・リアル', 'Omani Rial', 'オマーン', 'Oman', 1),
    ('PAB', 'パナマ・バルボア', 'Panamanian Balboa', 'パナマ', 'Panama', 1),
    ('PEN', 'ペルー・ソル', 'Peruvian Sol', 'ペルー', 'Peru', 1),
    ('PGK', 'パプアニューギニア・キナ', 'Papua New Guinean Kina', 'パプアニューギニア', 'Papua New Guinea', 1),
    ('PHP', 'フィリピン・ペソ', 'Philippine Peso', 'フィリピン', 'Philippines', 1),
    ('PKR', 'パキスタン・ルピー', 'Pakistani Rupee', 'パキスタン', 'Pakistan', 1),
    ('PLN', 'ポーランド・ズロチ', 'Polish Złoty', 'ポーランド', 'Poland', 1),
    ('PYG', 'パラグアイ・グアラニー', 'Paraguayan Guaraní', 'パラグアイ', 'Paraguay', 1),
    ('QAR', 'カタール・リヤル', 'Qatari Riyal', 'カタール', 'Qatar', 1),
    ('RON', 'ルーマニア・レウ', 'Romanian Leu', 'ルーマニア', 'Romania', 1),
    ('RSD', 'セルビア・ディナール', 'Serbian Dinar', 'セルビア', 'Serbia', 1),
    ('RUB', 'ロシア・ルーブル', 'Russian Ruble', 'ロシア', 'Russia', 1),
    ('RWF', 'ルワンダ・フラン', 'Rwandan Franc', 'ルワンダ', 'Rwanda', 1),
    ('SAR', 'サウジアラビア・リヤル', 'Saudi Riyal', 'サウジアラビア', 'Saudi Arabia', 1),
    ('SBD', 'ソロモン諸島・ドル', 'Solomon Islands Dollar', 'ソロモン諸島', 'Solomon Islands', 1),
    ('SCR', 'セイシェル・ルピー', 'Seychellois Rupee', 'セイシェル', 'Seychelles', 1),
    ('SDG', 'スーダン・ポンド', 'Sudanese Pound', 'スーダン', 'Sudan', 1),
    ('SEK', 'スウェーデン・クローナ', 'Swedish Krona', 'スウェーデン', 'Sweden', 1),
    ('SGD', 'シンガポール・ドル', 'Singapore Dollar', 'シンガポール', 'Singapore', 1),
    ('SHP', 'セントヘレナ・ポンド', 'Saint Helena Pound', 'セントヘレナ', 'Saint Helena', 1),
    ('SLE', 'シエラレオネ・レオネ', 'Sierra Leonean Leone', 'シエラレオネ', 'Sierra Leone', 1),
    ('SLL', 'シエラレオネ・レオネ', 'Sierra Leonean Leone', 'シエラレオネ', 'Sierra Leone', 0),
    ('SOS', 'ソマリア・シリング', 'Somali Shilling', 'ソマリア', 'Somalia', 1),
    ('SRD', 'スリナム・ドル', 'Surinamese Dollar', 'スリナム', 'Suriname', 1),
    ('SSP', '南スーダン・ポンド', 'South Sudanese Pound', '南スーダン', 'South Sudan', 1),
    ('STN', 'サントメ・プリンシペ・ドブラ', 'São Tomé and Príncipe Dobra', 'サントメ・プリンシペ', 'São Tomé and Príncipe', 1),
    ('SYP', 'シリア・ポンド', 'Syrian Pound', 'シリア', 'Syria', 1),
    ('SZL', 'エスワティニ・リランゲニ', 'Eswatini Lilangeni', 'エスワティニ', 'Eswatini', 1),
    ('THB', 'タイ・バーツ', 'Thai Baht', 'タイ', 'Thailand', 1),
    ('TJS', 'タジキスタン・ソモニ', 'Tajikistani Somoni', 'タジキスタン', 'Tajikistan', 1),
    ('TMT', 'トルクメニスタン・マナット', 'Turkmenistan Manat', 'トルクメニスタン', 'Turkmenistan', 1),
    ('TND', 'チュニジア・ディナール', 'Tunisian Dinar', 'チュニジア', 'Tunisia', 1),
    ('TOP', 'トンガ・パアンガ', 'Tongan Paʻanga', 'トンガ', 'Tonga', 1),
    ('TRY', 'トルコ・リラ', 'Turkish Lira', 'トルコ', 'Turkey', 1),
    ('TTD', 'トリニダード・トバゴ・ドル', 'Trinidad and Tobago Dollar', 'トリニダード・トバゴ', 'Trinidad and Tobago', 1),
    ('TVD', 'ツバル・ドル', 'Tuvaluan Dollar', 'ツバル', 'Tuvalu', 1),
    ('TWD', '新台湾ドル', 'New Taiwan Dollar', '台湾', 'Taiwan', 1),
    ('TZS', 'タンザニア・シリング', 'Tanzanian Shilling', 'タンザニア', 'Tanzania', 1),
    ('UAH', 'ウクライナ・グリフニャ', 'Ukrainian Hryvnia', 'ウクライナ', 'Ukraine', 1),
    ('UGX', 'ウガンダ・シリング', 'Ugandan Shilling', 'ウガンダ', 'Uganda', 1),
    ('USD', 'アメリカ・ドル', 'United States Dollar', 'アメリカ合衆国', 'United States', 1),
    ('UYU', 'ウルグアイ・ペソ', 'Uruguayan Peso', 'ウルグアイ', 'Uruguay', 1),
    ('UZS', 'ウズベキスタン・ソム', 'Uzbekistani So\'m', 'ウズベキスタン', 'Uzbekistan', 1),
    ('VES', 'ベネズエラ・ボリバール・ソベラノ', 'Venezuelan Bolívar Soberano', 'ベネズエラ', 'Venezuela', 1),
    ('VND', 'ベトナム・ドン', 'Vietnamese Đồng', 'ベトナム', 'Vietnam', 1),
    ('VUV', 'バヌアツ・バツ', 'Vanuatu Vatu', 'バヌアツ', 'Vanuatu', 1),
    ('WST', 'サモア・タラ', 'Samoan Tālā', 'サモア', 'Samoa', 1),
    ('XAF', '中央アフリカCFAフラン', 'Central African CFA Franc', '中央アフリカ', 'CEMAC', 1),
    ('XCD', '東カリブ・ドル', 'East Caribbean Dollar', '東カリブ諸国', 'Organisation of Eastern Caribbean States', 1),
    ('XDR', '特別引出権', 'Special Drawing Rights', '国際通貨基金', 'International Monetary Fund', 1),
    ('XOF', '西アフリカCFAフラン', 'West African CFA franc', '西アフリカ', 'CFA', 1),
    ('XPF', 'CFPフラン', 'CFP Franc', 'フランス海外領土', 'Collectivités d\'Outre-Mer', 1),
    ('YER', 'イエメン・リアル', 'Yemeni Rial', 'イエメン', 'Yemen', 1),
    ('ZAR', '南アフリカ・ランド', 'South African Rand', '南アフリカ', 'South Africa', 1),
    ('ZMW', 'ザンビア・クワチャ', 'Zambian Kwacha', 'ザンビア', 'Zambia', 1),
    ('ZWL', 'ジンバブエ・ドル', 'Zimbabwean Dollar', 'ジンバブエ', 'Zimbabwe', 1);