package com.moneyme.moneymebackend.controller;

import com.moneyme.moneymebackend.dto.request.CreateGroupRequest;
import com.moneyme.moneymebackend.dto.response.CreateGroupResponse;
import com.moneyme.moneymebackend.service.GroupService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/groups")
@RequiredArgsConstructor
public class GroupController {
    private final GroupService service;

    @PostMapping
    public ResponseEntity<CreateGroupResponse> createGroup(
            // TODO: Add validation if jwt is generated by auth server or not.
            @RequestHeader("Authorization") String token,
            @RequestBody CreateGroupRequest request
    ) {
        CreateGroupResponse response = service.createGroup(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }
}
