package com.moneyme.moneymebackend.controller;

import com.moneyme.moneymebackend.dto.request.CreateGroupRequest;
import com.moneyme.moneymebackend.dto.response.CreateOrGetGroupResponse;
import com.moneyme.moneymebackend.service.GroupService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/groups")
@RequiredArgsConstructor
public class GroupController {
    private final GroupService service;

    @GetMapping("/{uuid}")
    public ResponseEntity<CreateOrGetGroupResponse> getGroupInfo(
            // TODO: Add validation if jwt is generated by auth server or not.
            @RequestHeader("Authorization") String token,
            @PathVariable String uuid
    ) {
        CreateOrGetGroupResponse response = service.getGroupInfo(uuid);
        return ResponseEntity.ok(response);
    }

    @PostMapping
    public ResponseEntity<CreateOrGetGroupResponse> createGroup(
            // TODO: Add validation if jwt is generated by auth server or not.
            @RequestHeader("Authorization") String token,
            @RequestBody CreateGroupRequest request
    ) {
        CreateOrGetGroupResponse response = service.createGroup(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }
}
