package com.moneyme.moneymebackend.controller;

import com.moneyme.moneymebackend.dto.request.CreateUserRequest;
import com.moneyme.moneymebackend.dto.response.CreateUserResponse;
import com.moneyme.moneymebackend.service.UserService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RequiredArgsConstructor
@RequestMapping("/users")
@RestController
public class UserController {
    private final UserService service;

    @PostMapping
    public ResponseEntity<CreateUserResponse> createUser(
            // TODO: Add validation is uuid is generated by auth server or not.
            @RequestHeader String uuid,
            @RequestBody CreateUserRequest request
    ) {
        CreateUserResponse response = service.createUser(uuid, request);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }
}
