package com.moneyme.moneymebackend.controller;

import com.moneyme.moneymebackend.dto.response.UserResponseDTO;
import com.moneyme.moneymebackend.dto.request.UserRequestDTO;
import com.moneyme.moneymebackend.service.UserService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.UUID;

import static com.moneyme.moneymebackend.constants.ApiConstants.HEADER_AUTHORIZATION;
import static com.moneyme.moneymebackend.constants.ApiConstants.PATH_USERS;

@RequiredArgsConstructor
@RequestMapping(PATH_USERS)
@RestController
public class UserController {
    private final UserService service;

    @PostMapping
    public ResponseEntity<UserResponseDTO> createUser(
            @RequestHeader(HttpHeaders.AUTHORIZATION) String idToken,
            @RequestBody UserRequestDTO request) {
        UserResponseDTO response = service.createUser(idToken, request);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    @PatchMapping("/{userId}")
    public ResponseEntity<UserResponseDTO> updateUserInfo(
            // TODO: Add validation if jwt is generated by auth server or not.
            @RequestHeader(HEADER_AUTHORIZATION) String idToken,
            @PathVariable("userId") UUID userId,
            @RequestBody UserRequestDTO request) {
        UserResponseDTO response = service.updateUserInfo(idToken, userId, request);
        return ResponseEntity.ok(response);
    }
    @GetMapping("/{userId}")
    public ResponseEntity<UserResponseDTO> getUserInfo(
            @RequestHeader(HEADER_AUTHORIZATION) String idToken,
            @PathVariable("userId") UUID userId
    ) {
        UserResponseDTO response = service.getUserInfo(idToken, userId);
        return ResponseEntity.ok(response);
    }
}

