package com.moneyme.moneymebackend.controller;

import com.moneyme.moneymebackend.dto.request.CreateOrUpdateUserRequest;
import com.moneyme.moneymebackend.dto.response.UserResponse;
import com.moneyme.moneymebackend.service.UserService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RequiredArgsConstructor
@RequestMapping("/users")
@RestController
public class UserController {
    private final UserService service;

    @PostMapping
    public ResponseEntity<UserResponse> createUser(
            // TODO: Add validation if jwt is generated by auth server or not.
            @RequestHeader("Authorization") String token,
            @RequestBody CreateOrUpdateUserRequest request
    ) {
        UserResponse response = service.createUser(token, request);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    @PatchMapping("/{uuid}")
    public ResponseEntity<UserResponse> updateUserInfo(
            // TODO: Add validation if jwt is generated by auth server or not.
            @RequestHeader("Authorization") String token,
            @PathVariable String uuid,
            @RequestBody CreateOrUpdateUserRequest request
    ) {
        UserResponse response = service.updateUserInfo(token, uuid, request);
        return ResponseEntity.ok(response);
    }
}
