package com.moneyme.moneymebackend.service;

import com.google.firebase.auth.FirebaseAuthException;
import com.google.firebase.auth.FirebaseToken;
import com.moneyme.moneymebackend.dto.request.UserRequestDTO;
import com.moneyme.moneymebackend.dto.response.UserResponseDTO;
import com.moneyme.moneymebackend.entity.UserEntity;
import com.moneyme.moneymebackend.repository.UserRepository;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.UUID;

@Service
@RequiredArgsConstructor
public class UserService {
    private final UserRepository repository;

    @Transactional
    public UserResponseDTO createUser(UserRequestDTO request) {
        UserEntity user = UserEntity.builder()
                .uuid(UUID.randomUUID())
                .name(request.getUserName())
                .email(request.getEmail())
                .uid(request.getUid())
                .build();

        UserEntity savedUser = repository.save(user);

        return UserResponseDTO.from(savedUser);
    }

    @Transactional
    public UserResponseDTO updateUserInfo(String token, UUID userId, UserRequestDTO request) {
        // TODO: get-auth-user-id from JWT generated by Firebase.
        String authUserId = "authUserIdUpdated";

        UserEntity user = repository.findById(userId).orElseThrow(() -> new IllegalArgumentException("user not found"));

        user.setName(request.getUserName());
        user.setEmail(request.getEmail());
        user.setUid(authUserId);

        UserEntity savedUser = repository.save(user);

        return UserResponseDTO.from(savedUser);
    }

    public UserResponseDTO getUserInfo(String token, UUID userId) {
        UserEntity user = repository.findById(userId).orElseThrow(() -> new IllegalArgumentException("user not found"));

        return UserResponseDTO.from(user);
    }

}
