package com.moneyme.moneymebackend.service;

import com.moneyme.moneymebackend.dto.request.CreateOrUpdateUserRequest;
import com.moneyme.moneymebackend.dto.response.UserResponse;
import com.moneyme.moneymebackend.entity.UserEntity;
import com.moneyme.moneymebackend.repository.UserRepository;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.UUID;

@Service
@RequiredArgsConstructor
public class UserService {
    private final UserRepository repository;

    @Transactional
    public UserResponse createUser(String token, CreateOrUpdateUserRequest request) {
        // TODO: get-auth-user-id from JWT generated by Firebase.
        String authUserId = "authUserIdCreated";

        UserEntity user = UserEntity.builder()
                .uuid(UUID.randomUUID())
                .name(request.getUserName())
                .email(request.getEmail())
                .authUserId(authUserId)
                .build();

        UserEntity savedUser = repository.save(user);

        return UserResponse.from(savedUser);
    }

    @Transactional
    public UserResponse updateUserInfo(String token, String uuid, CreateOrUpdateUserRequest request) {
        // TODO: get-auth-user-id from JWT generated by Firebase.
        String authUserId = "authUserIdUpdated";

        UserEntity user = repository.findByUuid(UUID.fromString(uuid));

        user.setName(request.getUserName());
        user.setEmail(request.getEmail());
        user.setAuthUserId(authUserId);

        UserEntity savedUser = repository.save(user);

        return UserResponse.from(savedUser);
    }

}
